### PR TITLE
[Merged by Bors] - Add ‘knobby’ and ‘dots’ pipe kinds

### PR DESCRIPTION
**Pull request by arzg**

### CODE REVIEW

**Comment by arzg** [comment]
Ideally `dots` would have a width of 2, just like emoji, as the horizontal density of dots is currently too high. 

Screen Shot 2021-03-04 at 4 54 30 pm

I’ll make that change once this PR is merged.

**Comment by arzg** [comment]
I tried braille characters, but it doesn’t look very good
Screen Shot 2021-03-04 at 5 00 50 pm

**Comment by arzg** [comment]
I thought emoji arrows would be cool, but it seems that they are two code points, meaning they have to be represented as strings instead of individual characters. In a separate PR I’ll convert all the pipe kind code to use `str`s instead of `char`s

Screen Shot 2021-03-04 at 5 02 46 pm

Screen Shot 2021-03-04 at 5 03 49 pm

Also, I’m not sure why my terminal isn’t rendering the emoji arrows as emoji.

**Comment by CookieCoder15** [comment]
Proposed changes for after this PR sound good!

**Review by CookieCoder15 — APPROVED** [review]

**Pull request closed without merging**
