### PR TITLE
[Merged by Bors] - Remove unneeded ‘pub’s and ‘mut’s

### PR DESCRIPTION
**Pull request by arzg**

### CODE REVIEW

**Comment by arzg** [comment]
It looks like all the uses of `Terminal` in `model` are just to get the terminal’s size, so after this PR is merged I’ll create another one that removes `model`’s dependency on the `terminal` crate, and just pass in the terminal size where appropriate.

**Review by CookieCoder15 — APPROVED** [review]
LGTM 🐲

**Comment by arzg** [comment]
> It looks like all the uses of `Terminal` in `model` are just to get the terminal’s size, so after this PR is merged I’ll create another one that removes `model`’s dependency on the `terminal` crate, and just pass in the terminal size where appropriate.

I’ve done this in #32.

**Pull request closed without merging**
