### PR TITLE
[Merged by Bors] - Reset screen on resize

### LINKED ISSUE #9: Redraw threshold is inaccurate
Rather than measuring the coverage of the screen, all we do is measure the number of times the screen has refreshed. Ideally we should instead store the contents of the screen, and measure what portion of the screen’s cells have something on them.

### PR DESCRIPTION
**Pull request by arzg**
Fixes #9.

### CODE REVIEW

**Comment by arzg** [comment]
The `Screen` isn’t updated on resize, so this will break when the window is resized.

**Comment by arzg** [comment]
This PR also fixes #1, since `ticks` is no longer necessary.

**Comment by CookieCoder15** [comment]
This PR now also fixes #2.

**Review by CookieCoder15 — APPROVED** [review]
LGTM 😎

@arzg any other comments before merging?

**Comment by arzg** [comment]
Nope, seems good to me. bors r+

**Comment by arzg** [comment]
Uhhh, bors?

**Pull request closed without merging**
